steps:

  - id: "install go"
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'sum']
    env: ['GOPATH=.']
  - id: "test go"
    name: 'gcr.io/cloud-builders/go'
    args: ['test', 'sum']
    env: ['GOPATH=.']
  - id: "build docker"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/gosum', '.']

images: ['gcr.io/$PROJECT_ID/gosum']