steps:

  - id: "install go"
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'sum']
    env: ['GOPATH=.']
  - id: "test go"
    name: 'gcr.io/cloud-builders/go'
    args: ['test', 'sum']
    env: ['GOPATH=.']