
version: '3'

services:

  go:
    image: golang:1.12.6-alpine3.10
    container_name: go
    restart: always
    tty: true
    volumes:
      - "./src:/go/src/"
    working_dir: /go/src/sum/
    command: go test

  gobuild:
    build: .
    container_name: gobuild
    restart: always
    tty: true